version: '3' 
services:
  emby:
    image: lovechen/embyserver:latest  # 使用最新版本的 lovechen/embyserver 镜像
    container_name: emby               # 容器名称设置为 emby
    restart: always                    # 容器总是重新启动
    ports:
      - '8096:8096'                   # 将容器的 8096 端口映射到主机的 8096 端口
      - '8920:8920'                   # 将容器的 8920 端口映射到主机的 8920 端口
      - '1900:1900/udp'               # 将容器的 1900 UDP 端口映射到主机的 1900 UDP 端口
      - '7359:7359/udp'               # 将容器的 7359 UDP 端口映射到主机的 7359 UDP 端口
    volumes:
      - /volume1/docker/emby/config/:/config              # 将主机上的 ./config 目录挂载到容器的 /config
      - /volume1/docker/emby/data/:/data      # 将主机上的 /pt/downloads/link 目录挂载到容器的 /data
    environment:
      - UID=0                         # 设置容器用户 ID 为 0 (通常是 root)
      - GID=0                         # 设置容器组 ID 为 0 (通常是 root)
      - GIDLIST=0                     # 设置容器组 ID 列表为 0
    devices:
      - /dev/dri:/dev/dri             # 将主机的 /dev/dri 设备挂载到容器

